<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var $block \Magento\Catalog\Block\Product\Image */
/** @var $escaper \Magento\Framework\Escaper */
?>

<img class="photo image cloudinary-lazyload <?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
    <?= $escaper->escapeHtml($block->getCustomAttributes()) ?>
    src="<?= /* @noEscape */ $block->getLazyloadPlaceholder() ?>"
    data-original="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
    width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= /* @noEscape */ $block->stripTags($block->getLabel(), null, true) ?>" />
