<?php
/**
* Product media data template
*
* @var $block Cloudinary\Cloudinary\Block\VideoSettings
*/
?>
<style>
    .cld_video_player-dimensions.vjs-fluid:not(.vjs-audio-only-mode){
        padding-top: 95% !important;
    }
    .product-video.cld-product-video {
        position: static;
        height: initial;
        width: initial;
    }
</style>
<script id="cld_video_settings" type="application/json">
    <?= /* @noEscape */ json_encode($block->getVideoSettings()) ?>
</script>
<?php
$cloudinaryGalleryHelper = $this->helper('Cloudinary\Cloudinary\Helper\ProductGalleryHelper');
?>
<?php if ($cloudinaryGalleryHelper->isHyvaThemeEnabled()): ?>
    <script src="<?= /* @noEscape */ $block->getViewFileUrl('Cloudinary_Cloudinary::js/hyva/cloudinary-video-support.js') ?>"></script>
<?php endif; ?>
