<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 /** @var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content */
?>
<?php
$cloudinaryMLwidgetOprions = $block->getCloudinaryMediaLibraryWidgetOptions();
?>

<div class="media-gallery-modal" data-mage-init='{"mediabrowser": <?= $block->escapeHtml($block->getFilebrowserSetupObject()) ?>}'>
    <div class="page-main-actions">
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-action-buttons">
                    <?= $block->getButtonsHtml() ?>
                </div>
            </div>
        </div>
    </div>
    <div class="side-col"><?= $block->getChildHtml('wysiwyg_images.tree') ?></div>
    <div class="main-col">
        <div id="error-message" data-action="show-error"></div>
        <?php if ($cloudinaryMLwidgetOprions): ?>
            <div>
                [Cloudinary Button]
                <pre>
                    <?php print_r(json_decode($cloudinaryMLwidgetOprions)); ?>
                </pre>
            </div><br>
        <?php endif; ?>
        <div id="contents-uploader" class="contents-uploader"><?= $block->getChildHtml('wysiwyg_images.uploader') ?></div>
        <div id="contents"></div>
    </div>
</div>
