<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 /** @var $block \Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content */
/**  @var $escaper \Magento\Framework\Escaper  */
?>
<?php
$cloudinaryMLwidgetOprions = $block->getCloudinaryMediaLibraryWidgetOptions();
?>

<div class="media-gallery-modal" data-mage-init='{"mediabrowser": <?= $escaper->escapeHtml($block->getFilebrowserSetupObject()) ?>}'>
    <div class="page-main-actions">
        <div class="page-actions">
            <div class="page-actions-inner">
                <div class="page-action-buttons">
                    <?= /* @noEscape */ $block->getButtonsHtml() ?>
                </div>
            </div>
        </div>
    </div>
    <div class="side-col">
        <div><?= /* @noEscape */ $block->getChildHtml('wysiwyg_images.tree') ?></div>
    </div>
    <div class="main-col">
        <div id="error-message" data-action="show-error"></div>
        <?php if ($cloudinaryMLwidgetOprions): ?>
            <button id="media_gallery_add_from_cloudinary_button"
                title="<?= $escaper->escapeHtml(__('Add from Cloudinary')) ?>"
                data-role="add-from-cloudinary-button"
                type="button"
                data-mage-init='{"cloudinaryMediaLibraryModal": <?= $cloudinaryMLwidgetOprions ?>}'
                class="action-secondary add-from-cloudinary-button cloudinary-button-with-logo lg-margin-bottom">
                <span><?= $escaper->escapeHtml(__('Add from Cloudinary')) ?></span>
            </button>
        <?php endif; ?>
        <div id="contents-uploader" class="contents-uploader"><?= /* @noEscape  */ $block->getChildHtml('wysiwyg_images.uploader') ?></div>
        <div id="contents"></div>
    </div>
</div>
